before_script:
  # paths to local or network installations (the riscv toolchain and 
  # verilator are not built in the ci job as in travis)
  - export QUESTASIM_HOME=/usr/pack/modelsim-10.6b-kgf/questasim/
  - export QUESTASIM_VERSION=-10.6b
  - export QUESTASIM_FLAGS=-noautoldlibpath
  - export CXX=g++-7.2.0 CC=gcc-7.2.0
  - export RISCV=/usr/scratch2/larain1/gitlabci/riscv_install
  - export VERILATOR_ROOT=/usr/scratch2/larain1/gitlabci/verilator-3.924
  # setup dependent paths
  - export PATH=${RISCV}/bin:$VERILATOR_ROOT/bin:${PATH}
  - export LIBRARY_PATH=$RISCV/lib
  - export LD_LIBRARY_PATH=$RISCV/lib:/usr/pack/gcc-7.2.0-af/linux-x64/lib64/
  - export C_INCLUDE_PATH=$RISCV/include:$VERILATOR_ROOT/include:/usr/pack/gcc-7.2.0-af/linux-x64/include
  - export CPLUS_INCLUDE_PATH=$RISCV/include:$VERILATOR_ROOT/include:/usr/pack/gcc-7.2.0-af/linux-x64/include
  # number of parallel jobs to use for make commands and simulation
  - export NUM_JOBS=4
  - ci/make-tmp.sh
  - git submodule update --init --recursive
   
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test_std

# prepare
build:
  stage: build
  script:
    - ci/build-riscv-tests.sh
    - ci/get-torture.sh
    - make clean
    - make torture-gen
  artifacts:
      paths:
        - tmp 

# rv64ui-p-* and rv64ui-v-* tests    
run-asm-tests-questa:
  stage: test_std
  script:
    - make -j${NUM_JOBS} run-asm-tests 
  dependencies:
    - build

run-benchmarks-questa:
  stage: test_std
  script:
    - make -j${NUM_JOBS} run-benchmarks 
  dependencies:
    - build    

torture:
  stage: test_std
  script:
    - make torture-rtest
  dependencies:
    - build
