before_script:
  # paths to local or network installations (the riscv toolchain and 
  # verilator are not built in the ci job as in travis)
  - export QUESTASIM_HOME=/usr/pack/modelsim-10.6b-kgf/questasim/
  - export QUESTASIM_VERSION=-10.6b
  - export QUESTASIM_FLAGS=-noautoldlibpath
  - export CXX=g++-7.2.0 CC=gcc-7.2.0
  - export RISCV=/usr/scratch2/larain1/gitlabci/riscv_install
  - export VERILATOR_ROOT=/usr/scratch2/larain1/gitlabci/verilator-3.924
  # setup dependent paths
  - export PATH=${RISCV}/bin:$VERILATOR_ROOT/bin:${PATH}
  - export LIBRARY_PATH=$RISCV/lib
  - export LD_LIBRARY_PATH=$RISCV/lib:/usr/pack/gcc-7.2.0-af/linux-x64/lib64/
  - export C_INCLUDE_PATH=$RISCV/include:$VERILATOR_ROOT/include:/usr/pack/gcc-7.2.0-af/linux-x64/include
  - export CPLUS_INCLUDE_PATH=$RISCV/include:$VERILATOR_ROOT/include:/usr/pack/gcc-7.2.0-af/linux-x64/include
  # number of parallel jobs to use for make commands and simulation
  - export NUM_JOBS=4
  - ci/make-tmp.sh
  - git submodule update --init --recursive
   
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - standard
  - serpent

# prepare
build:
  stage: build
  script:
    - ci/build-riscv-tests.sh
    - ci/get-torture.sh
    - make clean
    - make torture-gen
  artifacts:
      paths:
        - tmp 

asm-quest:
  stage: standard
  script:
    - make -j${NUM_JOBS} run-asm-tests batch-mode=1
  dependencies:
    - build

amo-quest:
  stage: standard
  script:
    - make -j${NUM_JOBS} run-amo-tests batch-mode=1
  dependencies:
    - build
    
bench-quest:
  stage: standard
  script:
    - make -j${NUM_JOBS} run-benchmarks batch-mode=1
  dependencies:
    - build    

# rv64ui-p-* tests
asm1-ver:
  stage: standard
  script:
    - make -j${NUM_JOBS} run-asm-tests1-verilator 
  dependencies:
    - build

# rv64ui-v-* tests
asm2-ver:
  stage: standard
  script:
    - make -j${NUM_JOBS} run-asm-tests2-verilator 
  dependencies:
    - build    

# atomics
amo-ver:
  stage: standard
  script:
    - make -j${NUM_JOBS} run-amo-verilator 
  dependencies:
    - build    

bench-ver:
  stage: standard
  script:
    - make -j${NUM_JOBS} run-benchmarks-verilator 
  dependencies:
    - build

torture:
  stage: standard
  script:
    - make torture-rtest
    - make torture-rtest-verilator
  dependencies:
    - build

