#   Copyright (c) 2024 OpenHW Group
#   Copyright (c) 2024 Thales
#   SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
#   Author: Abdessamii Oukalrazqou

#  Range control
pmpaddr : 
    range : 16
pmpcfg :
    range : 4
 #  Exclude mode 
exclude :         
    key : priv_mode       
    cond : S
exclude :         
    key : priv_mode       
    cond : U
    

