#   Copyright (c) 2024 OpenHW Group
#   Copyright (c) 2024 Thales
#   SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
#   Author: Abdessamii Oukalrazqou

mip:
    rv32:
        meip:
            type:
                ro_variable:
                      - 0x0:0x1    
        mtip:
            type:
                ro_variable:
                      - 0x0:0x1              
mie:
    rv32:
        meie:
            type:
                ro_variable:
                      - 0x0:0x1    
        mtie:
            type:
                ro_variable:
                      - 0x0:0x1 
mstatus :
    rv32 : 
        mie : 
            type :
                    wlrl:
                      - 0x0:0x1
        mpie :
            type:
                    wlrl:
                      - 0x0:0x1
 # Exclude mode 
exclude :         
   key : priv_mode       
   cond : S
exclude :         
    key : priv_mode       
    cond : U
