#   Copyright (c) 2024 OpenHW Group
#   Copyright (c) 2024 Thales
#   SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
#   Author: Abdessamii Oukalrazqou


misa:
    reset-val: 123475      
mcycle: 
      reset-val: 123475 
mvendorid:
    description: '' 
misa:
    rv32:
        mxl:
            shadow_type: ''
pmp : 
    reset-val: 123475
